# Generated by Django 4.1.3 on 2022-11-15 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('mobile', models.IntegerField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('otp', models.IntegerField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.IntegerField(max_length=100, null=True)),
                ('Bank_name', models.IntegerField(blank=True, max_length=50, null=True)),
                ('IFSC_Code', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('use', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wallet.person')),
                ('Balance', models.IntegerField(blank=True, null=True)),
                ('add_money', models.IntegerField(max_length=100, null=True)),
                ('withdraw', models.IntegerField(max_length=100, null=True)),
            ],
        ),
    ]
