# Generated by Django 4.1.3 on 2022-11-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField(max_length=100, null=True, unique=True)),
                ('otp', models.IntegerField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('Balance', models.IntegerField(blank=True, null=True)),
                ('Bank_name', models.IntegerField(blank=True, max_length=50, null=True)),
                ('IFSC_Code', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('use', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wallet.person')),
                ('account_number', models.IntegerField(blank=True, max_length=100, null=True)),
                ('Transaction_ID', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
