# Generated by Django 4.1.3 on 2022-11-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('mobile', models.IntegerField(max_length=100, null=True)),
                ('otp', models.IntegerField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('Balance', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(max_length=100, null=True)),
                ('account', models.IntegerField(max_length=100, null=True)),
                ('add_money', models.IntegerField(max_length=100, null=True)),
                ('withdraw', models.IntegerField(max_length=100, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
