# Generated by Django 4.1.3 on 2022-11-11 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='id',
            new_name='Id',
        ),
    ]
