# Generated by Django 4.1.3 on 2022-11-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='send_money',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
