# Generated by Django 4.1.3 on 2022-11-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='mobile',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
