# Generated by Django 4.1.3 on 2022-12-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='transaction_id',
        ),
    ]
