# Generated by Django 4.1.4 on 2022-12-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='marks',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
