# Generated by Django 4.1.4 on 2022-12-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_person_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='marks',
            field=models.IntegerField(blank=True, default='0', max_length=5, null=True),
        ),
    ]
