# Generated by Django 4.1.3 on 2022-11-28 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_send_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('Transaction_ID', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wallet.wallet')),
            ],
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='Transaction_ID',
        ),
    ]
