# Generated by Django 4.1.4 on 2022-12-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_person_chemistry_person_english_person_maths_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='chemistry',
            field=models.IntegerField(blank=True, default='0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='english',
            field=models.IntegerField(blank=True, default='0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='maths',
            field=models.IntegerField(blank=True, default='0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='physics',
            field=models.IntegerField(blank=True, default='0', max_length=50, null=True),
        ),
    ]
