# Generated by Django 4.1.4 on 2022-12-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_remove_person_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='marks',
            field=models.IntegerField(blank=True, default='0', max_length=5, null=True),
        ),
    ]
